# Generated by Django 2.2.1 on 2020-05-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezpay', '0002_auto_20200508_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
