# Generated by Django 2.2.1 on 2020-05-08 21:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tezpay', '0003_receipts_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=uuid.uuid4, max_length=555, null=True)),
                ('price', models.FloatField(blank=True, default=400, null=True)),
                ('status', models.CharField(choices=[(1, 'Waiting'), (2, 'Progress'), (3, 'Done'), (4, 'Canceled')], default=1, max_length=555, null=True)),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
    ]
