# Generated by Django 2.2.1 on 2020-05-08 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tezpay', '0004_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tezpay.Receipts'),
        ),
    ]
