# Generated by Django 2.2.1 on 2020-05-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezpay', '0005_delivery_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='address',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='delivery_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
