# Generated by Django 2.2.1 on 2020-05-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezpay', '0007_receipts_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payed',
        ),
        migrations.AddField(
            model_name='receipts',
            name='payed',
            field=models.CharField(choices=[(1, 'Yes'), (2, 'No')], max_length=555, null=True),
        ),
    ]
