# Generated by Django 2.2.1 on 2020-05-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezpay', '0008_auto_20200508_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='payed',
            field=models.CharField(blank=True, choices=[(1, 'Yes'), (2, 'No')], max_length=555, null=True),
        ),
    ]
