# Generated by Django 2.2.1 on 2020-05-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezpay', '0009_auto_20200508_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='category',
            field=models.ManyToManyField(to='tezpay.Category'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='payed',
            field=models.CharField(blank=True, choices=[(1, 'Yes'), (2, 'No')], default=2, max_length=555, null=True),
        ),
    ]
