# Generated by Django 2.2.1 on 2020-05-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezpay', '0010_auto_20200509_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
