# Generated by Django 2.2.1 on 2020-05-11 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tezpay', '0011_orders_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='shop_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tezpay.ShopType'),
        ),
    ]
