# Generated by Django 2.2.1 on 2020-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tezpay', '0012_receipts_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='address',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='receipts',
            name='payment_url',
            field=models.CharField(max_length=555, null=True),
        ),
    ]
