# Generated by Django 2.2.1 on 2020-05-20 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tezpay', '0013_auto_20200519_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
